name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with: 
        python-version: 3.14

    - run: pip install --no-cache-dir -r ./app/requirements.txt

    - run: pytest

    - run: docker build -t myapp:${{ github.sha }} .
